services:
  - type: web
    name: horror-recommender-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: "gunicorn app:app"
    autoDeploy: true
    runtime: python
